import axios from '@/api/shared/http'

export const CreateCircle = (data) => axios.post('/api/circle', data)
export const UpdateCircle = (id, data) => axios.put(`/api/circle/${id}`, data)
export const DeleteCircle = (id) => axios.delete(`/api/circle/${id}`)
export const GetCircleById = (id) => axios.get(`/api/circle/${id}`)
export const GetAllCircles = (params) => axios.get('/api/circle', { params })
export const GetCirclesByCreator = (creatorId) => axios.get(`/api/circle/creator/${creatorId}`)
export const GetPublicCircles = () => axios.get('/api/circle/public')
export const GetCirclesByType = (type) => axios.get(`/api/circle/type/${type}`)
export const GetCircleByName = (name) => axios.get(`/api/circle/name/${name}`)
export const CheckCircleNameExists = (name) => axios.get(`/api/circle/exists/${name}`)
export const GetCircleMembers = (circleId) => axios.get(`/api/circle/${circleId}/members`)
export const CircleJoin = (circleId, data) => axios.post(`/api/circle/${circleId}/join`, data)
export const CircleLeave = (circleId, data) => axios.post(`/api/circle/${circleId}/leave`, data)
// Deprecated aliases kept only for compatibility with old imports.
// Public pages should use CircleJoin / CircleLeave directly.
export const JoinCircle = (circleId, data) => CircleJoin(circleId, data)
export const LeaveCircle = (circleId, data) => CircleLeave(circleId, data)
export const GetCircleAdmins = (circleId) => axios.get(`/api/circle/${circleId}/admins`)
export const CheckCircleMembership = (circleId, userId) => axios.get(`/api/circle/${circleId}/members/${userId}/check`)
export const SetCircleMemberRole = (circleId, userId, data) => axios.put(`/api/circle/${circleId}/members/${userId}/role`, data)
export const RemoveCircleMember = (circleId, userId) => axios.delete(`/api/circle/${circleId}/members/${userId}`)
export const GetCirclePosts = (circleId, params) => axios.get(`/api/circle/${circleId}/posts`, { params })
export const GetAllCirclePosts = (params) => axios.get('/api/circle/posts/all', { params })
export const GetUserCirclePosts = (userId, params) => axios.get(`/api/circle/user/${userId}/posts`, { params })
export const DeleteUserCirclePosts = (userId) => axios.delete(`/api/circle/user/${userId}/posts`)
export const GetCircleCommentById = (id) => axios.get(`/api/circle/comments/${id}`)
export const DeleteCircleComment = (id) => axios.delete(`/api/circle/comments/${id}`)
export const CreateCircleComment = (data) => axios.post('/api/circle/comments', data)
export const LikeCircleComment = (id) => axios.post(`/api/circle/comments/${id}/like`)
export const GetCirclePostReplies = (postId, params) => axios.get(`/api/circle/posts/${postId}/replies`, { params })
export const GetCircleCommentReplies = (commentId, params) => axios.get(`/api/circle/comments/${commentId}/replies`, { params })
