import axios from 'axios'

// 用户认证模块
export const sendVerifyCode = (data) => axios.post('/register/send-verify-code', data)
export const register = (data) => axios.post('/register', data)
export const login = (data) => axios.post('/login', data)
export const logout = () => axios.post('/logout')
export const refreshToken = (data) => axios.post('/api/token/refresh', data)
export const sendPasswordResetVerifyCode = (data) => axios.post('/password-reset/send-verify-code', data)
export const verifyPasswordResetToken = (params) => axios.get('/password-reset/verify-token', { params })
export const resetPassword = (data) => axios.post('/password-reset/reset', data)

// 用户管理模块
export const createUser = (data) => axios.post('/api/users', data)
export const updateUser = (id, data) => axios.put(`/api/users/${id}`, data)
export const deleteUser = (id) => axios.delete(`/api/users/${id}`)
export const getUserById = (id) => axios.get(`/api/users/${id}`)
export const getCurrentUser = () => axios.get('/api/users/current')
export const updateCurrentUser = (data) => axios.put('/api/users/updatemine', data)
export const changePassword = (data) => axios.put('/api/users/changepwd', data)
export const changeEmail = (data) => axios.put('/api/users/changeemail', data)
export const changeUsername = (data) => axios.put('/api/users/changeusername', data)
export const verifyCurrentPassword = (data) => axios.post('/api/users/verify-pwd', data)
export const bindThirdPartyAccount = (id, data) => axios.post(`/api/users/${id}/bind-third`, data)
export const getUserPublicInfo = (id) => axios.get(`/api/users/${id}/public`)

// 角色权限模块
export const getAllRoles = () => axios.get('/api/roles')
export const getRoleById = (id) => axios.get(`/api/roles/${id}`)
export const createRole = (data) => axios.post('/api/roles', data)
export const updateRole = (id, data) => axios.put(`/api/roles/${id}`, data)
export const deleteRole = (id) => axios.delete(`/api/roles/${id}`)
export const getAllPermissions = () => axios.get('/api/permissions')
export const getPermissionById = (id) => axios.get(`/api/permissions/${id}`)
export const createPermission = (data) => axios.post('/api/permissions', data)
export const updatePermission = (id, data) => axios.put(`/api/permissions/${id}`, data)
export const deletePermission = (id) => axios.delete(`/api/permissions/${id}`)
export const assignPermissionsToRole = (roleId, data) => axios.post(`/api/roles/${roleId}/permissions`, data)
export const getRolePermissions = (roleId) => axios.get(`/api/roles/${roleId}/permissions`)
export const assignRolesToUser = (userId, data) => axios.put(`/api/users/${userId}/assign-roles`, data)
export const getUserRoles = (userId) => axios.get(`/api/users/${userId}/roles`)
export const getUserPermissions = (userId) => axios.get(`/api/users/${userId}/permissions`)

// 菜单管理模块
export const getAllMenus = () => axios.get('/api/menus')
export const getMenuById = (id) => axios.get(`/api/menus/${id}`)
export const createMenu = (data) => axios.post('/api/menus', data)
export const createRootMenu = (data) => axios.post('/api/menus/root', data)
export const getSubMenus = (parentId) => axios.get(`/api/menus/${parentId}/children`)
export const updateMenu = (id, data) => axios.put(`/api/menus/${id}`, data)
export const deleteMenu = (id) => axios.delete(`/api/menus/${id}`)
export const getMenusPage = (params) => axios.get('/api/admin/menus/page', { params })
export const assignMenusToRole = (roleId, data) => axios.put(`/api/roles/${roleId}/assign-menus`, data)
export const assignButtonsToRole = (roleId, data) => axios.put(`/api/roles/${roleId}/assign-buttons`, data)

// 博客管理模块
export const createBlog = (data) => axios.post('/api/blogs', data)
export const getBlogById = (id) => axios.get(`/api/blogs/${id}`)
export const getAllBlogs = (params) => axios.get('/api/blogs', { params })
export const updateBlog = (id, data) => axios.put(`/api/blogs/${id}`, data)
export const deleteBlog = (id) => axios.delete(`/api/blogs/${id}`)
export const searchBlogs = (params) => axios.get('/api/blogs/search', { params })
export const getBlogsByAuthorId = (authorId) => axios.get(`/api/blogs/author/${authorId}`)
export const searchBlogsByTag = (params) => axios.get('/api/blogs/search/tag', { params })
export const searchBlogsByAuthor = (params) => axios.get('/api/blogs/search/author', { params })
export const unpublishBlog = (id) => axios.put(`/api/blogs/${id}/unpublish`)
export const republishBlog = (id) => axios.put(`/api/blogs/${id}/republish`)
export const getUnpublishedBlogs = () => axios.get('/api/blogs/unpublished')
export const saveBlogDraft = (data) => axios.post('/api/blogs/draft', data)
export const getBlogDrafts = () => axios.get('/api/blogs/draft')
export const sortBlogs = (type, params) => axios.get(`/api/blogs/sort/${type}`, { params })
export const downloadBlog = (id, data) => axios.post(`/api/blogs/${id}/download`, data)

// 博客互动模块
export const likeBlog = (id) => axios.post(`/api/blogs/${id}/like`)
export const addLike = (data) => axios.post('/api/interactive/likes', data)
export const deleteLike = (id) => axios.delete(`/api/interactive/likes/${id}`)
export const getLikeById = (id) => axios.get(`/api/interactive/likes/${id}`)
export const checkUserLiked = (userId, targetType, targetId) => axios.get(`/api/interactive/likes/user/${userId}/target/${targetType}/${targetId}`)
export const getLikesByTarget = (targetType, targetId) => axios.get(`/api/interactive/likes/target/${targetType}/${targetId}`)
export const getLikesByUser = (userId) => axios.get(`/api/interactive/likes/user/${userId}`)
export const getAllLikes = () => axios.get('/api/interactive/likes')
export const collectBlog = (blogId) => axios.post(`/api/blogs/${blogId}/collect`)
export const cancelCollectBlog = (blogId) => axios.delete(`/api/blogs/${blogId}/collect`)
export const getMyCollections = () => axios.get('/api/blogs/my-collections')
export const isCollected = (blogId) => axios.get(`/api/blogs/${blogId}/is-collected`)
export const addComment = (data) => axios.post('/api/interactive/comments', data)
export const getCommentById = (id) => axios.get(`/api/interactive/comments/${id}`)
export const getCommentsByPost = (postId) => axios.get(`/api/interactive/comments/post/${postId}`)
export const replyComment = (data) => axios.post('/api/interactive/comments/reply', data)
export const deleteComment = (id) => axios.delete(`/api/interactive/comments/${id}`)
export const getCommentReplies = (commentId) => axios.get(`/api/interactive/comments/${commentId}/replies`)
export const getAllComments = () => axios.get('/api/interactive/comments')

// 圈子模块
export const createCircle = (data) => axios.post('/api/circle', data)
export const updateCircle = (id, data) => axios.put(`/api/circle/${id}`, data)
export const deleteCircle = (id) => axios.delete(`/api/circle/${id}`)
export const getCircleById = (id) => axios.get(`/api/circle/${id}`)
export const getAllCircles = () => axios.get('/api/circle')
export const getCirclesByCreator = (creatorId) => axios.get(`/api/circle/creator/${creatorId}`)
export const getPublicCircles = () => axios.get('/api/circle/public')
export const getCirclesByType = (type) => axios.get(`/api/circle/type/${type}`)
export const getCircleByName = (name) => axios.get(`/api/circle/name/${name}`)
export const checkCircleNameExists = (name) => axios.get(`/api/circle/exists/${name}`)
export const getCircleMembers = (circleId) => axios.get(`/api/circle/${circleId}/members`)
export const joinCircle = (circleId) => axios.post(`/api/circle/${circleId}/members`)
export const leaveCircle = (circleId) => axios.delete(`/api/circle/${circleId}/members`)
export const setCircleAdmins = (circleId, data) => axios.put(`/api/circle/${circleId}/admins`, data)
export const getCircleConversation = (circleId) => axios.get(`/api/circle/${circleId}/conversation`)

// 会话消息模块
export const createConversation = (data) => axios.post('/api/conversation', data)
export const getConversationById = (id) => axios.get(`/api/conversation/${id}`)
export const getAllConversations = () => axios.get('/api/conversation')
export const deleteConversation = (id) => axios.delete(`/api/conversation/${id}`)
export const sendMessage = (conversationId, data) => axios.post(`/api/conversation/${conversationId}/messages`, data)
export const getConversationMessages = (conversationId) => axios.get(`/api/conversation/${conversationId}/messages`)
export const getMessagesSince = (conversationId, params) => axios.get(`/api/conversation/${conversationId}/messages/since`, { params })
export const markMessageAsRead = (messageId) => axios.put(`/api/conversation/messages/${messageId}/read`)
export const markAllMessagesAsRead = (conversationId) => axios.put(`/api/conversation/${conversationId}/read-all`)
export const getUnreadCount = (conversationId) => axios.get(`/api/conversation/${conversationId}/unread-count`)

// 通知模块
export const createNotification = (data) => axios.post('/api/notifications', data)
export const getMyNotifications = () => axios.get('/api/notifications/my')
export const getMyUnreadNotificationCount = () => axios.get('/api/notifications/unread-count')
export const markNotificationAsRead = (id) => axios.put(`/api/notifications/${id}/read`)
export const markAllNotificationsAsRead = () => axios.put('/api/notifications/read-all')
export const deleteNotification = (id) => axios.delete(`/api/notifications/${id}`)
export const getUserNotifications = (userId) => axios.get(`/api/notifications/user/${userId}`)

// 标签与公共模块
export const getAllRegions = () => axios.get('/api/common/regions')
export const getRegionById = (id) => axios.get(`/api/common/regions/${id}`)
export const getAllTags = () => axios.get('/api/common/tags')
export const getTagById = (id) => axios.get(`/api/common/tags/${id}`)
export const getHotTags = () => axios.get('/api/common/tags/hot')
export const getTagsPage = (params) => axios.get('/api/admin/tags/page', { params })
export const createTag = (data) => axios.post('/api/admin/tags', data)
export const updateTag = (id, data) => axios.put(`/api/admin/tags/${id}`, data)
export const deleteTag = (id) => axios.delete(`/api/admin/tags/${id}`)

// 文件与系统配置模块
export const uploadFile = (data) => axios.post('/api/upload', data)
export const deleteFile = (fileId) => axios.delete(`/api/upload/${fileId}`)
export const getSystemConfig = () => axios.get('/api/config')
export const updateSystemConfig = (data) => axios.put('/api/config', data)
export const healthCheck = () => axios.get('/api/health')

// 后台管理模块
export const getUsersPage = (params) => axios.get('/api/admin/users/page', { params })
export const batchDeleteUsers = (data) => axios.delete('/api/admin/users/batch', { data })
export const batchUpdateUserStatus = (data) => axios.put('/api/admin/users/batch-status', data)
export const muteUser = (id, data) => axios.put(`/api/admin/users/${id}/mute`, data)
export const getPendingReviewBlogs = (params) => axios.get('/api/admin/review/blogs/pending', { params })
export const approveBlog = (id) => axios.put(`/api/admin/review/blogs/${id}/approve`)
export const rejectBlog = (id, data) => axios.put(`/api/admin/review/blogs/${id}/reject`, data)
export const batchReviewBlogs = (data) => axios.put('/api/admin/review/blogs/batch', data)
export const createReport = (data) => axios.post('/api/reports', data)
export const getReportsPage = (params) => axios.get('/api/admin/reports/page', { params })
export const handleReport = (id, data) => axios.put(`/api/reports/${id}/handle`, data)
export const getOperationLogsPage = (params) => axios.get('/api/admin/logs/operations/page', { params })
export const getLoginLogsPage = (params) => axios.get('/api/admin/logs/logins/page', { params })
export const exportOperationLogs = (params) => axios.get('/api/admin/logs/operations/export', { params, responseType: 'blob' })
export const exportLoginLogs = (params) => axios.get('/api/admin/logs/logins/export', { params, responseType: 'blob' })
export const getSystemLogs = () => axios.get('/api/logs')
export const getUserLogs = (userId) => axios.get(`/api/logs/user/${userId}`)
export const getOperationLogDetail = (id) => axios.get(`/api/admin/logs/operations/${id}`)
export const cleanExpiredLogs = (data) => axios.delete('/api/admin/logs/clean', { data })
export const getUserGrowthStats = (params) => axios.get('/api/admin/stats/users/growth', { params })
export const getBlogPublishStats = (params) => axios.get('/api/admin/stats/blogs/published', { params })
export const getSystemActivityStats = (params) => axios.get('/api/admin/stats/system/activity', { params })
export const getStats = () => axios.get('/api/stats')
export const getUserRegisterStats = () => axios.get('/api/stats/users')
export const getBlogStats = () => axios.get('/api/stats/blogs')