# ????
spring.application.name=it-main

# ?????
server.port=18080

# ?????
spring.datasource.url=jdbc:mysql://localhost:3306/it_data?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=zy050618
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA配置
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=false

# ????
logging.level.root=info
logging.level.com.alikeyou=debug
# ?? Hibernate SQL ??
spring.jpa.show-sql=false
# ?? Hibernate ????? WARN????????????
logging.level.org.hibernate=WARN
# ????????????????? SQL ???????
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type=WARN

# JWT??
jwt.secret=your-secret-key
jwt.expiration=3600000

# ???????
spring.mail.host=smtp.qq.com
spring.mail.port=587
spring.mail.username=2159997489@qq.com
spring.mail.password=wvuymcraoueudjja
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true